#!/bin/sh
export PATH=$PATH:/Library/Frameworks/Mono.framework/Versions/4.4.2/bin
export PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/External/pkgconfig:/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/pkgconfig:/Library/Frameworks/Mono.framework/Versions/4.4.2/share/pkgconfig:$PKG_CONFIG_PATH
exec /Library/Frameworks/Mono.framework/Versions/4.4.2/bin/mono $MONO_OPTIONS /Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/mcs.exe "$@"
